### ISSUE TITLE
Home Assistant Integration?

### ISSUE THREAD

**Issue by hzpz** [ChrisHaPunkt/stihl-imow-webapi#12]
Thank you for this project, it is working flawlessly so far 👍 

You mention a Home Assistant integration based on this project. I would be very much interested in that! Is it something that already exists or are you still working on it? Or is it even a private project?

**Comment by ChrisHaPunkt** [comment]
Just edited the Readme to provide a link to the HA Integration ;) https://github.com/ChrisHaPunkt/ha-stihl-imow
